# frozen_string_literal: true

require "rails_helper"
require "fileutils"
require "tmpdir"

RSpec.describe "semantic snapshot boot lifecycle" do
  let(:tmp_dir) { Dir.mktmpdir("maglev-snapshot") }

  around do |example|
    original_path = Maglev.configuration.semantic_snapshot_path
    Maglev::SemanticSnapshotStore.reset!
    example.run
  ensure
    Maglev.configuration.semantic_snapshot_path = original_path
    Maglev::SemanticSnapshotStore.reset!
  end

  after { FileUtils.remove_entry(tmp_dir) if File.directory?(tmp_dir) }

  def write_snapshot(yaml, name: "semantic-layer.generated.yml")
    path = File.join(tmp_dir, name)
    File.write(path, yaml)
    path
  end

  def current_build_fingerprint
    Maglev::SemanticSnapshotBuilder.build_input_fingerprint(Rails.root)
  end

  def valid_snapshot_yaml(
    build_fingerprint: current_build_fingerprint,
    generator_version: Maglev::VERSION
  )
    entries = Maglev::Registry.entries
    graph = Maglev::SemanticGraph.new(nodes: [], edges: [], evidence: [], claims: [])
    Maglev::SemanticSnapshot.new(
      graph: graph,
      generator_version: generator_version,
      build_input_fingerprint: build_fingerprint,
      registry_compatibility_fingerprint:
        Maglev::SemanticSnapshotBuilder.registry_compatibility_fingerprint(entries)
    ).to_yaml
  end

  describe "disabled (nil semantic_snapshot_path)" do
    it "leaves v0.3 behavior unchanged even when a file exists at the default path" do
      write_snapshot(valid_snapshot_yaml)
      Maglev.configuration.semantic_snapshot_path = nil

      Maglev::SemanticSnapshotStore.reload!

      expect(Maglev.semantic_snapshot).to be_nil
    end
  end

  describe "valid enabled snapshot" do
    it "loads and freezes the snapshot without discovery or provider calls" do
      path = write_snapshot(valid_snapshot_yaml)
      Maglev.configuration.semantic_snapshot_path = path
      expect(Maglev::SemanticDiscovery).not_to receive(:new)

      Maglev::SemanticSnapshotStore.reload!

      snapshot = Maglev.semantic_snapshot
      expect(snapshot).to be_a(Maglev::SemanticSnapshot)
      expect(snapshot).to be_frozen
      expect(snapshot.graph).to be_frozen
      expect(snapshot.graph.nodes).to be_frozen
      expect(snapshot.registry_compatibility_fingerprint).to eq(
        Maglev::SemanticSnapshotBuilder.registry_compatibility_fingerprint(Maglev::Registry.entries)
      )
    end

    it "recomputes and verifies the registry compatibility fingerprint at boot" do
      path = write_snapshot(valid_snapshot_yaml)
      Maglev.configuration.semantic_snapshot_path = path

      Maglev::SemanticSnapshotStore.reload!

      expect(Maglev.semantic_snapshot.registry_compatibility_fingerprint).to eq(
        Maglev::SemanticSnapshotBuilder.registry_compatibility_fingerprint(Maglev::Registry.entries)
      )
    end

    it "fails boot when the build input fingerprint is stale" do
      path = write_snapshot(valid_snapshot_yaml(build_fingerprint: "sha256:stale-build"))
      Maglev.configuration.semantic_snapshot_path = path

      expect { Maglev::SemanticSnapshotStore.reload! }
        .to raise_error(Maglev::ConfigurationError, /build fingerprint.*rebuild/)
    end

    it "fails boot when the snapshot was built by an incompatible Maglev version" do
      path = write_snapshot(valid_snapshot_yaml(generator_version: "0.3.0"))
      Maglev.configuration.semantic_snapshot_path = path

      expect { Maglev::SemanticSnapshotStore.reload! }
        .to raise_error(Maglev::ConfigurationError, /generated by Maglev 0\.3\.0.*rebuild/)
    end
  end

  describe "missing file" do
    it "fails boot with an actionable configuration error" do
      Maglev.configuration.semantic_snapshot_path = File.join(tmp_dir, "does-not-exist.yml")

      expect { Maglev::SemanticSnapshotStore.reload! }
        .to raise_error(Maglev::ConfigurationError, /not found/)
    end

    it "wraps snapshot filesystem errors in an actionable configuration error" do
      path = write_snapshot(valid_snapshot_yaml)
      Maglev.configuration.semantic_snapshot_path = path
      allow_any_instance_of(Pathname).to receive(:binread).and_raise(Errno::EACCES, path)

      expect { Maglev::SemanticSnapshotStore.reload! }
        .to raise_error(Maglev::ConfigurationError, /could not be read.*rebuild/)
    end
  end

  describe "malformed YAML" do
    it "fails boot with an actionable configuration error" do
      path = write_snapshot("--- []\n")
      Maglev.configuration.semantic_snapshot_path = path

      expect { Maglev::SemanticSnapshotStore.reload! }
        .to raise_error(Maglev::ConfigurationError, /invalid/)
    end
  end

  describe "incompatible registry fingerprint" do
    it "fails boot with an actionable configuration error" do
      graph = Maglev::SemanticGraph.new(nodes: [], edges: [], evidence: [], claims: [])
      stale = Maglev::SemanticSnapshot.new(
        graph: graph,
        generator_version: Maglev::VERSION,
        build_input_fingerprint: "sha256:stale-build",
        registry_compatibility_fingerprint: "sha256:stale-registry"
      )
      path = write_snapshot(stale.to_yaml)
      Maglev.configuration.semantic_snapshot_path = path

      expect { Maglev::SemanticSnapshotStore.reload! }
        .to raise_error(Maglev::ConfigurationError, /fingerprint/)
    end
  end

  describe "development reload" do
    it "replaces the active snapshot when the replacement validates" do
      original_path = write_snapshot(valid_snapshot_yaml, name: "original.yml")
      Maglev.configuration.semantic_snapshot_path = original_path
      Maglev::SemanticSnapshotStore.reload!
      original = Maglev.semantic_snapshot
      expect(original).not_to be_nil

      replacement_path = write_snapshot(valid_snapshot_yaml, name: "replacement.yml")
      Maglev.configuration.semantic_snapshot_path = replacement_path

      Maglev::SemanticSnapshotStore.reload!

      expect(Maglev.semantic_snapshot).not_to equal(original)
      expect(Maglev.semantic_snapshot.build_input_fingerprint).to eq(current_build_fingerprint)
      expect(Maglev.semantic_snapshot).to be_frozen
    end

    it "preserves the current valid snapshot when the replacement is invalid" do
      original_path = write_snapshot(valid_snapshot_yaml, name: "original.yml")
      Maglev.configuration.semantic_snapshot_path = original_path
      Maglev::SemanticSnapshotStore.reload!
      original = Maglev.semantic_snapshot
      expect(original).not_to be_nil

      invalid_path = write_snapshot("--- []\n", name: "invalid.yml")
      Maglev.configuration.semantic_snapshot_path = invalid_path

      Maglev::SemanticSnapshotStore.reload!

      expect(Maglev.semantic_snapshot).to equal(original)
    end

    it "preserves the current valid snapshot when the replacement has a stale fingerprint" do
      original_path = write_snapshot(valid_snapshot_yaml, name: "original.yml")
      Maglev.configuration.semantic_snapshot_path = original_path
      Maglev::SemanticSnapshotStore.reload!
      original = Maglev.semantic_snapshot

      graph = Maglev::SemanticGraph.new(nodes: [], edges: [], evidence: [], claims: [])
      stale = Maglev::SemanticSnapshot.new(
        graph: graph,
        generator_version: Maglev::VERSION,
        build_input_fingerprint: "sha256:stale",
        registry_compatibility_fingerprint: "sha256:wrong-registry"
      )
      stale_path = write_snapshot(stale.to_yaml, name: "stale.yml")
      Maglev.configuration.semantic_snapshot_path = stale_path

      Maglev::SemanticSnapshotStore.reload!

      expect(Maglev.semantic_snapshot).to equal(original)
    end
  end

  describe "Rails lifecycle" do
    it "loads through the dummy application's to_prepare callback" do
      Maglev::Registry.rebuild!
      path = write_snapshot(valid_snapshot_yaml)
      Maglev.configuration.semantic_snapshot_path = path

      Rails.application.reloader.prepare!

      expect(Maglev.semantic_snapshot).to be_a(Maglev::SemanticSnapshot)
    end

    it "keeps the first valid snapshot active in production" do
      original_path = write_snapshot(valid_snapshot_yaml, name: "original.yml")
      replacement_path = write_snapshot(valid_snapshot_yaml, name: "replacement.yml")
      allow(Rails.env).to receive(:production?).and_return(true)

      Maglev.configuration.semantic_snapshot_path = original_path
      Maglev::SemanticSnapshotStore.reload!
      original = Maglev.semantic_snapshot
      Maglev.configuration.semantic_snapshot_path = replacement_path
      Maglev::SemanticSnapshotStore.reload!

      expect(Maglev.semantic_snapshot).to equal(original)
    end
  end
end
