# frozen_string_literal: true

require_relative "maglev/version"
require_relative "maglev/configuration"
require_relative "maglev/errors"
require_relative "maglev/authorization"
require_relative "maglev/provider_call"
require_relative "maglev/knowledge_config"
require_relative "maglev/snapshot"
require_relative "maglev/snapshot_builder"
require_relative "maglev/chunker"
require_relative "maglev/embedding_adapter"
require_relative "maglev/adapters/ruby_llm_embedding"
require_relative "maglev/generation_adapter"
require_relative "maglev/adapters/ruby_llm_generation"
require_relative "maglev/extracted_document"
require_relative "maglev/attachment_extractor"
require_relative "maglev/adapters/ruby_llm_attachment_extractor"
require_relative "maglev/search_result"
require_relative "maglev/vector_stores/base"
require_relative "maglev/vector_stores/document"
require_relative "maglev/vector_stores/memory"
require_relative "maglev/vector_stores/pgvector"
require_relative "maglev/response"
require_relative "maglev/prompt_builder"
require_relative "maglev/context_assembler"
require_relative "maglev/context_preview"
require_relative "maglev/indexer"
require_relative "maglev/reindex_job"
require_relative "maglev/retriever"
require_relative "maglev/schema_compiler"
require_relative "maglev/dependency_graph"
require_relative "maglev/content_source_graph"
require_relative "maglev/answerer"

require_relative "maglev/railtie" if defined?(Rails::Railtie)
