# frozen_string_literal: true

require_relative "errors"
require_relative "semantic_snapshot"
require_relative "semantic_snapshot_builder"

module Maglev
  # Thread-safe singleton that holds the active immutable SemanticSnapshot.
  #
  # Lifecycle:
  # - nil semantic_snapshot_path  → v0.3 behavior (active is nil)
  # - valid path at boot          → loads, verifies build and registry fingerprints, freezes
  # - invalid path at boot        → raises ConfigurationError (fail closed)
  # - valid path on dev reload    → atomically replaces the active snapshot
  # - invalid path on dev reload  → preserves the current valid snapshot
  class SemanticSnapshotStore
    class << self
      # Returns the currently active frozen SemanticSnapshot, or nil when the
      # semantic layer is not enabled.
      def active
        mutex.synchronize { @active }
      end

      # Loads (or reloads) the snapshot from the configured path.
      #
      # Called from Maglev::Railtie to_prepare on every Rails preparation cycle:
      # once at boot in production, and on each code reload in development.
      def reload!
        current = mutex.synchronize { @active }
        return current if production? && current

        path = Maglev.configuration.semantic_snapshot_path

        if path.nil?
          mutex.synchronize { @active = nil }
          return
        end

        snapshot = load_and_verify!(path)
        mutex.synchronize do
          return @active if production? && @active

          @active = snapshot
        end
      rescue ConfigurationError => error
        current = mutex.synchronize { @active }
        raise if current.nil?

        log_warning("Maglev semantic snapshot reload failed; preserving current snapshot: #{error.message}")
      end

      # Clears the store. Intended for test isolation.
      def reset!
        mutex.synchronize { @active = nil }
      end

      private

      def load_and_verify!(path)
        resolved = nil
        resolved = resolve_path(path)

        unless resolved.file?
          raise ConfigurationError,
            "Maglev semantic snapshot not found at #{resolved}; " \
            "run bin/rails maglev:semantics:build or set semantic_snapshot_path to nil"
        end

        yaml = resolved.binread
        snapshot = SemanticSnapshot.load(yaml)
        verify_build_compatibility!(snapshot, resolved)
        verify_registry_compatibility!(snapshot, resolved)
        snapshot
      rescue SemanticSnapshot::ValidationError => error
        raise ConfigurationError,
          "Maglev semantic snapshot at #{resolved} is invalid: #{error.message}"
      rescue SystemCallError, TypeError, ArgumentError => error
        location = resolved || path.inspect
        raise ConfigurationError,
          "Maglev semantic snapshot at #{location} could not be read: #{error.message}; " \
          "rebuild it with bin/rails maglev:semantics:build or correct semantic_snapshot_path"
      end

      def verify_build_compatibility!(snapshot, resolved)
        unless snapshot.generator_version == Maglev::VERSION
          raise ConfigurationError,
            "Maglev semantic snapshot at #{resolved} was generated by Maglev " \
            "#{snapshot.generator_version}, but the running version is #{Maglev::VERSION}; " \
            "run bin/rails maglev:semantics:build to rebuild"
        end

        current_fingerprint = SemanticSnapshotBuilder.build_input_fingerprint(application_root)
        return if current_fingerprint == snapshot.build_input_fingerprint

        raise ConfigurationError,
          "Maglev semantic snapshot at #{resolved} has build fingerprint " \
          "#{snapshot.build_input_fingerprint} but the current application produces " \
          "#{current_fingerprint}; run bin/rails maglev:semantics:build to rebuild"
      end

      def verify_registry_compatibility!(snapshot, resolved)
        current_fingerprint = SemanticSnapshotBuilder.registry_compatibility_fingerprint(Registry.entries)
        return if current_fingerprint == snapshot.registry_compatibility_fingerprint

        raise ConfigurationError,
          "Maglev semantic snapshot at #{resolved} has registry fingerprint " \
          "#{snapshot.registry_compatibility_fingerprint} but the current registry " \
          "produces #{current_fingerprint}; run bin/rails maglev:semantics:build to rebuild"
      end

      def resolve_path(path)
        candidate = Pathname(path)
        return candidate.expand_path if candidate.absolute?

        application_root.join(candidate).expand_path
      end

      def application_root
        rails_root || Pathname(Dir.pwd)
      end

      def rails_root
        return unless defined?(Rails) && Rails.respond_to?(:root)

        Rails.root
      end

      def log_warning(message)
        logger = Maglev.configuration.logger
        if logger
          logger.warn(message)
        else
          Kernel.warn(message)
        end
      end

      def production?
        defined?(Rails) && Rails.respond_to?(:env) && Rails.env.production?
      end

      def mutex
        @mutex ||= Mutex.new
      end
    end
  end
end
